# BToks optimized dataset layer
# Inherit BToks metadata semantics and only override optimized weights here.

_inherit_: ./btoks_mmeb_train.yaml

ImageNet_1K:
  weight: 3

N24News:
  weight: 2

HatefulMemes:
  weight: 1

VOC2007:
  weight: 1

SUN397:
  weight: 1

OK-VQA:
  weight: 1

A-OKVQA:
  weight: 1

DocVQA:
  weight: 2

InfographicsVQA:
  weight: 1

ChartQA:
  weight: 1

Visual7W:
  weight: 2

VisDial:
  weight: 3

CIRR:
  weight: 1

VisualNews_t2i:
  weight: 3

VisualNews_i2t:
  weight: 3

MSCOCO_t2i:
  weight: 3

MSCOCO_i2t:
  weight: 3

NIGHTS:
  weight: 1

WebQA:
  weight: 1

MSCOCO:
  weight: 3

colpali_train_set:
  weight: 16

visrag-indomain:
  weight: 17

video_caption_300k:
  weight: 10

video_caption_300k-video:
  weight: 10

video_qa_240k:
  weight: 10
